const Image ={
    card1: require('../../img/card1.png'),
    card2: require('../../img/card2.png'),
    card3: require('../../img/card3.png'),
    card4: require('../../img/card4.png'),
    card5: require('../../img/card5.png'),
    card6: require('../../img/card6.png'),
    card7: require('../../img/card7.png'),
    card8: require('../../img/card8.png'),
    card9: require('../../img/card9.png'),
    card10: require('../../img/card10.png'),
    card11: require('../../img/card11.png'),
    card12: require('../../img/card12.png'),
    card13: require('../../img/card13.png'),
    card14: require('../../img/card14.png'),
    card15: require('../../img/card15.png'),
    card16: require('../../img/card16.png'),
    card17: require('../../img/card17.png'),
    card18: require('../../img/card18.png'),
    card19: require('../../img/card19.png'),
    card20: require('../../img/card20.png'),
    card21: require('../../img/card21.png'),
    card22: require('../../img/card22.png'),
    card23: require('../../img/card23.png'),
    card24: require('../../img/card24.png'),
    card25: require('../../img/card25.png'),
    card26: require('../../img/card26.png'),
    card27: require('../../img/card27.png'),
    card28: require('../../img/card28.png'),
    card29: require('../../img/card29.png'),
    card30: require('../../img/card30.png'),
    card31: require('../../img/card31.png'),
    card32: require('../../img/card32.png'),
    card33: require('../../img/card33.png'),
    card34: require('../../img/card34.png'),
    card35: require('../../img/card35.png'),
    card36: require('../../img/card36.png'),
    card37: require('../../img/card37.png'),
    card38: require('../../img/card38.png'),
    card39: require('../../img/card39.png'),
    card40: require('../../img/card40.png'),
    card41: require('../../img/card41.png'),
    card42: require('../../img/card42.png'),
    card43: require('../../img/card43.png'),
    card44: require('../../img/card44.png'),
    card45: require('../../img/card45.png'),
    card46: require('../../img/card46.png'),
    card47: require('../../img/card47.png'),
    card48: require('../../img/card48.png'),
    card49: require('../../img/card49.png'),
    card50: require('../../img/card50.png'),
    
    
}
export default Image;